name: moveapps-python-sdk
channels:
  - conda-forge
dependencies:
  - qgis
  - urllib3
  - pyproj
  - matplotlib
  - branca
  - folium
  - numpy
  - geopandas
  - movingpandas
  - shapely
  - scipy
  - pluggy
  - python-dotenv
  - python=3.11
  - deprecated
